### ISSUE TITLE
Obuilder's Dockerfiles should not continue to blank lines

### ISSUE THREAD

**Issue by dra27** [ocurrent/obuilder#65]
Merely picking a recent build [from opam-repo-ci](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/8bc561b126f334024823342e9249e1d4d7c70149/variant/distributions,alpine-3.12,leveldb.1.3.0), the `Dockerfile` includes a continuation to a blank line which generates a warning from `docker build`.

An easy fix for that one is probably just to trim the string - and possibly to reduce `(\r?\n)` to a single `\r?\n`?

**Comment by talex5** [comment]
Well, it's because opam-repo-ci gives it a command with a blank line at the end. OBuilder's behaviour seems reasonable to me, but Docker's doesn't. It seems to ignore the blank line and act as if the continuation applies to the line after that!

Perhaps it should be an error to attempt to convert such a command to a Dockerfile?

**Comment by talex5** [comment]
Closing as I think it's just a special-case of #66 (Dockerfile can't handle newlines in general).
